# Generated by Django 4.0.3 on 2022-04-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Amphi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=7)),
                ('born_on', models.DateField()),
                ('born_at', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrev', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('intitule', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('intitule', models.CharField(max_length=255)),
                ('credit', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.amphi')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('mgp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('complete_credit', models.PositiveIntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.academicyear')),
                ('etudiant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transcript.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.amphi')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('decision', models.CharField(default=None, max_length=10)),
                ('grade', models.CharField(default=None, max_length=5)),
                ('etudiant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transcript.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.ue')),
            ],
        ),
        migrations.AddField(
            model_name='amphi',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.filiere'),
        ),
        migrations.AddField(
            model_name='amphi',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.level'),
        ),
    ]
