# Generated by Django 4.0.3 on 2022-04-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transcript.etudiant'),
        ),
        migrations.DeleteModel(
            name='Obtain',
        ),
    ]
