# Generated by Django 4.0.3 on 2022-04-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_transcript_etudiant_delete_obtain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='participate',
            name='evaluation',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='academicyear',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='academicyear',
            new_name='academic_year',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='exam',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='decision',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transcript.etudiant'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='grade',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Participate',
        ),
    ]
