# Generated by Django 4.0.3 on 2022-05-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0006_ue_hastp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ue',
            old_name='hasTp',
            new_name='has_tp',
        ),
    ]
