# Generated by Django 4.0.3 on 2022-05-24 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0007_rename_hastp_ue_has_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='amphi',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transcript.academicyear'),
            preserve_default=False,
        ),
    ]
