# Generated by Django 4.0.3 on 2022-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0011_rename_hash_transcript_cipher_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
