# Generated by Django 4.0.3 on 2022-06-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0012_transcript_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='hash',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='cipher_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
