# Generated by Django 4.0.3 on 2022-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0013_remove_transcript_hash_alter_transcript_cipher_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='hash',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
